name: PHP Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json
      run: composer validate

    - name: PHPUnit tests
      uses: php-actions/phpunit@v1
      with:
        configuration: phpunit.xml
        php_version: 7.4
        phpunit_version: 9

    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse lib/ --level=5
